version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services: 
  flask_app: 
    container_name: flask_app
    expose: 
      - 5000
    image: "djam36/app_flask:latest"
    ports: 
      - "5000:5000"
    restart: unless-stopped
  grafana: 
    container_name: grafana
    depends_on: 
      - prometheus
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=ADMIN
      - GF_USERS_ALLOW_SIGN_UP=false
    image: "grafana/grafana:latest"
    links: 
      - "prometheus:prometheus"
    restart: unless-stopped
    user: "472"
    volumes: 
      - "grafana_data:/var/lib/grafana"
  prometheus: 
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    container_name: prometheus
    expose: 
      - 9095
    image: "prom/prometheus:v2.1.0"
    ports: 
      - "9095:9095"
    restart: unless-stopped
    volumes: 
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
